name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Run a one-line script
      run: echo "Hello World"

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Calculate sum and difference of two numbers
      run: |
        # 数値aとbを仮定
        a=5
        b=10

        # 和を計算
        sum=$(($a + $b))
        echo "Sum of $a and $b is $sum"

        # 差を計算
        diff=$(($a - $b))
        echo "Difference between $a and $b is $diff"